### ISSUE TITLE
hardcoded to urbanists.social

### ISSUE THREAD

**Issue by codl** [samwightt/citadel#1]
hi, I tried to set up a copy of this tool but I couldn't log into my instance

after doing the oauth dance and being redirected to citadel, the next request went out to urbanists.social and was denied, since that's not the instance where i was trying to log in, and i was dumped back at the index

indeed it seems urbanists.social is hardcoded: https://github.com/samwightt/citadel/blob/1aa3fab055a909e02df689a5088d63403ab88708/src/lib/client.ts#L48-L52

**Comment by thibaultmol** [comment]
![image](https://github.com/samwightt/citadel/assets/1010226/a304c74c-f646-4e3c-86ec-d7770274a606)
probably why I'm also getting this error maybe

**Comment by thibaultmol** [comment]
Even though i auth'd using en.osm.town I also get the urbanists.social auth urls in my console. So i'm pretty sure it's the same problem 
![image](https://github.com/samwightt/citadel/assets/1010226/f4f44469-ac01-470a-b5f5-637ea60b57bd)

**Comment by samwightt** [comment]
OH LMAO THIS IS THE ISSUE LOLLLLLLLLLLLL

**Comment by samwightt** [comment]
This makes so much more sense LOL

**Comment by samwightt** [comment]
Okay, give it a try now and let me know if the fix I just pushed works! Make sure to enter just the domain (eg. `urbanists.social`, not `https://urbanists.social`).

**Comment by thibaultmol** [comment]
can confirm this fixed it :+1:  thx
