### ISSUE TITLE
Add most recent post to report?

### ISSUE THREAD

**Issue by thibaultmol** [samwightt/citadel#4]
While the instance admin is aware of reports made my mods and that they're valid.
It would be nice if it included atleast one post in the report for context, to show it was indeed one of the spam bots (like we're having now) for example
![image](https://github.com/samwightt/citadel/assets/1010226/aa0253e2-3173-41fc-94c1-1fe4b0fbfe82)

**Comment by samwightt** [comment]
Oo good idea! I can include the most recent post in it.

**Comment by samwightt** [comment]
Just added this! Thanks for the feature request!
